### PR TITLE
Setup ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Little CI Cocktail :)

https://travis-ci.org/AdrieanKhisbe/loop.el

### CODE REVIEW

**Comment by Wilfred** [comment]
Wow, thanks for doing this!

**Comment by AdrieanKhisbe** [comment]
You're welcome :)
I plan to do this is ht.el later

**Comment by AdrieanKhisbe** [comment]
you should add somewhere a tag so we have a build on melpa stable :)

**Comment by Wilfred** [comment]
Done :)

**Comment by AdrieanKhisbe** [comment]
great! :)

**Comment by AdrieanKhisbe** [comment]
(oh, just last thing: turn coveralls on ;)
https://coveralls.io)

**Comment by Wilfred** [comment]
Enabled: we're at 100% coverage!

**Comment by AdrieanKhisbe** [comment]
Well donne ;)

**Pull request merged**
